[40기 정재헌] ADD: 카카오 로그인 기능 구현 완료
wecode-bootcamp-korea/40-2nd-FF-backend pull request #3
Opened 2022-12-28 08:01 UTC by JasonJeongjaeheon

ADD: kakao login service api 기능
MODIFY: userDao query문 수정
FIX: FE & BE 통신 수정 완료

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카카오 로그인 api를 이용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- FE로부터 인증 코드를 전달 받아 카카오 인증 서버에 요청 보내기
- 인증 서버로 요청을 보낸 후, 카카오 accesstoken 받기
- 유저 정보를 얻기 위하여 받은 카카오 accesstoken을 카카오 resource server로 보내기
- 받은 유저 정보를 가지고 파인딩코드 내 DB서버와 확인하여 회원가입 및 JWT token 발급 과정 처리하기

<br />

## :: 테스트 결과 이미지
1. 인증 코드 및 서비스용 JWT 토큰 발급
![스크린샷 2022-12-28 오후 5 00 28](https://user-images.githubusercontent.com/116066497/209779025-fda6f69f-a9df-4d12-b4e2-9cba9a58dad0.png)

<br />

## :: 기타 질문 및 특이 사항
- 에러 처리에 대해서 좀 더 구체적인 에러 처리를 하고 싶은데, 아직 힘듭니다.

2022-12-30 06:41 UTC, Jon9Beom reviewed
'how to mock axios response in jest'와 같은 키워드로 구글링 하여 unit test code에서 axios에 대한 결과 값을 mocking하는 법을 참고해보시고 jest로 작성된 유닛 테스트 코드 꼭 추가해주세요-!

2022-12-30 06:41 UTC, Jon9Beom commented on api/controllers/userController.js
> +    res.status(200).json({accessToken:accessToken})
```suggestion
    return res.status(200).json({accessToken})
```
응답뒤에 더 실행할 로직이 없다면 return 해주세요. 추가로 작성하신 코드처럼 오브젝트에서 key와 value가 일치한다면 다음과 같이 쓸 수 있습니다.

2022-12-30 06:41 UTC, Jon9Beom commented on api/models/userDao.js
> +}
```suggestion
const createUser = async(kakaoUserInfo, res) => {
    return await appDataSource.query(
        `INSERT INTO 
            users (
                name,
                email,
                gender,
                social_id
            ) VALUES (
                ?,
                ?,
                ?,
                ?
            )
            `, [kakaoUserInfo.nickname, 
                kakaoUserInfo.email, 
                kakaoUserInfo.gender, 
                kakaoUserInfo.sub]
        )
}
```
dao는 CRUD에 맞춰서 naming을 해주시는게 일반적인 컨벤션입니다! (ex. getProduct, createReview)
또한 다음과 같이 꼭 변수를 선언하지 않고도 query를 할 수 있을 것 같아요 :)

2022-12-30 06:41 UTC, Jon9Beom commented on api/models/userDao.js
> +}
getUserSocialId라는건 유저의 소셜아이디를 get하겠다는 것 처럼 보일 수 있어서 조금 더 명확히 보이면 좋을 것 같아요-!

또한 어차피 query를 통해 return 되는 data가 특정 object 1개인데 배열로 감싸져 있는거라면 다음과 같이 작성하는 것이 코드 가독성에서 조금 더 나을 것 같습니다.
```suggestion
const getUserBySocialId = async(socialId) => {
    const [userInfo] = await appDataSource.query(
        `SELECT
            u.id,
            u.name,
            u.email,
            u.gender,
            u.social_id
        FROM users u
        WHERE u.social_id = ?
        `, [socialId]
    )
    return userInfo
}
```

2022-12-30 06:41 UTC, Jon9Beom commented on api/services/kakaoService.js
> +const getAccessTokenByKakao = async(code, res) => {
```suggestion
const getAccessTokenByKakao = async(code) => {
```
res는 parameter로 받을 필요가 있을까요?

2022-12-30 06:41 UTC, Jon9Beom commented on api/services/userService.js
> +    }
작성 잘해주셨네요 재헌님 :) 다만 if, else if에 대해서 다시 생각해보면 좋을 것 같습니다. 어차피 우리 로직은 `이거, 아니면 저거`의 이분법적인 로직인 것이기에 else if가 쓰일 필요가 없고 이미 if 문 안에서 조건문에 걸리지 않는다면 단지 다음 코드로 넘어갈 것 이기때문에 else 조차 필요가 없습니다.
```suggestion
    if(!userInfo){
                
        const newUser = await userDao.signUp(kakaoUserInfo)
        const payLoad = {userId: newUser.insertId}
        const accessToken = jwt.sign(
            payLoad,
            process.env.JWT_SECRET,
            { algorithm: process.env.ALGORITHM, expiresIn: process.env.JWT_EXPIRES_IN}
        )
        return accessToken   
    } 

    const payLoad = { userId: userInfo.id }
    const accessToken = jwt.sign(
        payLoad,
        process.env.JWT_SECRET,
        { algorithm: process.env.ALGORITHM, expiresIn: process.env.JWT_EXPIRES_IN } 
    )
    return accessToken
```

2022-12-30 06:45 UTC, sangwoong03 requested changes

2022-12-30 06:45 UTC, sangwoong03 commented on api/controllers/userController.js
> +    const code = req.headers.authorization
인가 코드로 우리 서비스 서버의 자격 증명을 확인하는 것이 아니기 때문에
query 혹은 code 자체를 받아도 될 것 같습니다.

```suggestion
    const code = req.query
```

2022-12-30 06:45 UTC, sangwoong03 commented on api/services/kakaoService.js
> +const getAccessTokenByKakao = async(code, res) => {
두번째 argument `res`는 불필요하므로 삭제하는 것이 좋겠습니다.
```suggestion
const getAccessTokenByKakao = async(code) => {
```

2022-12-30 06:45 UTC, sangwoong03 commented on api/services/kakaoService.js
> +const getUserInfoByKakao = async(getAccessTokenByKakao, res) => {
`getKakaoUserInfo()` 라는 함수명이 더 명확할 것 같습니다.

2022-12-30 06:45 UTC, sangwoong03 commented on api/services/userService.js
> +    const userInfo = await userDao.getUserSocialId(socialId)
```suggestion
    const user = await userDao.getUserBySocialId(socialId);
```
변수명, 함수명 수정하면 좋을 것 같아요!

2023-01-01 02:03 UTC, JasonJeongjaeheon commented
안녕하세요, 종범님! 요청 주신 테스트 기능 추가하여 push 하였습니다. 
카카오 리소서 서버에 userinfo를 받아 오는 테스트는 통과하였습니다.
다만 카카오 access token에 대한 테스트 부분에서 계속 fail을 반복하여 해당 부분에 대하여 확인 한 번 부탁 드리겠습니다.

2023-01-02 05:44 UTC, Jon9Beom commented
구두로 말씀드린 부분 수정되시면 라벨 변경해주세요 :)

2023-01-02 11:31 UTC, JasonJeongjaeheon commented
종범님 말씀해주신 내용 반영하여 수정하였습니다.
다만 npm test로 인해 나오는 에러 부분에 대해서는 완벽히 처리가 되었는지는 잘 모르겠습니다.
해당 부분에 대해서는 한 번 확인 부탁 드리겠습니다. 감사합니다!

2023-01-03 01:22 UTC, Jon9Beom commented
해당 코드에서 kakao api를 이용하여, token과 userInfo를 받아오는 부분을 다른 파일(ex. third-party-api.js)로 분리하는 것을 넘어서, 추후에는 클래스(OOP 기반)로 작성되어 어떠한 platform (kakao, google, apple, naver . . .)이 들어오더라도 재활용되거나 최소한의 수정만 이뤄질 수 있도록 refactoring + develop 되면 좋을 것 같습니다-! LGTM 👍

2023-01-03 01:22 UTC, merged